name: ERPNext CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          pip install flake8
          flake8 .


  test:
    runs-on: ubuntu-latest
    needs: lint

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          sudo apt-get update
          sudo apt-get install -y redis-server yarn

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: pip install frappe-bench

      - run: bench init frappe-bench --frappe-branch version-15

      - run: |
          cd frappe-bench
          bench new-site teststackerp --admin-password admin --db-root-password root
          bench get-app testerp2 $GITHUB_WORKSPACE
          bench --site teststackerp install-app testerp2

      - run: |
          cd frappe-bench
          bench --site teststackerp run-tests --app testerp2
